Repository andela/phoenix-bn-backend, pull requests merged in 2019-08, with the labels that each got.

#6 Setup dotenv for environment variables
  .envSample
  .gitignore
  package-lock.json
  package.json
Labels: Needs Review, good first issue

#15 Setup Unit Testing for functionalities
  .eslintrc~HEAD
  .gitignore
  package-lock.json
  package.json
  src/index.js
  src/routes/index.js
  src/tests/controllers/indexTest.js
  src/tests/models/indexTest.js
  src/tests/routes/indexTest.js
Labels: Needs Review

#13 #167765386 Setup docker for backend
  .dockerignore
  Dockerfile
  docker-compose.yml
Labels: Needs Review

#18 #167765377 setup PostgreSql for weTravel db
  .envSample
  .sequelizerc
  package-lock.json
  package.json
  src/database/config.js
  src/migrations/20190827125917-create-user.js
  src/models/User.js
  src/models/index.js
  src/models/user.js
Labels: Needs Review

#2 #167765381 Setup and Integrate Travis CI with README.md badge
  .travis.yml
  README.md
Labels: ready to merge

#23 Integrate Coveralls code coverage service
  .eslintrc~HEAD
  .gitignore
  .travis.yml
  README.md
  package-lock.json
  package.json
Labels: ready for merge

#20 #167765385 set up Swagger api documentation
  package-lock.json
  package.json
  src/index.js
  src/public/api-docs/swaggerDoc.json
Labels: ready for merge
